### ISSUE TITLE
[buster] Install fails during initial configuration with .ini ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/mumbleserver_ynh#33]
Not sure what happens but this line
```
murmurd -ini /var/www/mumbleserver/mumble-server.ini -supw $password 1
```

Results in: 
```
Warning: yunohost.hook <lambda> - [1415.1] <W>2020-03-17 00:21:37.575 ServerDB: Using SQLite's default rollback journal.
Warning: yunohost.hook <lambda> - [1415.1] <W>2020-03-17 00:21:38.503 Performed initial PBKDF2 benchmark. Will use  8000  iterations as default
Warning: yunohost.hook <lambda> - [1415.1] <W>2020-03-17 00:21:38.504 Generating new tables...
Warning: yunohost.hook <lambda> - [1415.1] <F>2020-03-17 00:21:38.625 Superuser password set on server 1
Error: yunohost.app app_install - [1415.1] Could not install mumbleserver: An error occurred inside the app installation script
```

Though it doesn't seem to say what's the real issue exactly ...

More info : https://ci-buster.nohost.me/ci/job/96

**Comment by maniackcrudelis** [comment]
There's actually no error, reason why the error isn't shown in the log.
That just because of a mistake in the code, murmurd exit(1) after the password is set instead of 0
The issue about it is here: https://github.com/mumble-voip/mumble/issues/3911

Meanwhile, we probably have no other choice than a || true...
